version: "2"

services:
  ddns:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/ddns/Dockerfile
    depends_on:
      - redis
    environment:
      DDNS_DOMAIN: d.example.net
      DDNS_SOA_DOMAIN: ddns.example.net
      DDNS_REDIS_HOST: redis:6379
      DDNS_CADDY_HOST: caddy:2019

  powerdns:
    restart: unless-stopped
    build:
      context: powerdns/
      dockerfile: Dockerfile
    depends_on:
      - ddns
    environment:
      PDNS_REMOTE_HTTP_HOST: "ddns:8053"

  redis:
    restart: unless-stopped
    image: redis:4-alpine

  caddy:
    restart: unless-stopped
    image: caddy:latest
    volumes:
      - "${PWD}/caddy/Caddyfile:/etc/Caddyfile"
      - "${PWD}/.caddy_mount:/root/.caddy"
